/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "stm32f446xx.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void)
{
	// task 3
	RCC->AHB1ENR |= RCC_AHB1ENR_GPIOBEN;	// allows clocking port B
	RCC->AHB1ENR |= RCC_AHB1ENR_GPIOAEN;	// allows clocking port A
	GPIOB->MODER |= 1 << 5*2;	// register 5B port
	GPIOA->MODER |= 1 << 8*2;	// register 8A port


    /* Loop forever */
	for(;;)
	{
		GPIOB->ODR ^= GPIO_ODR_OD5;
		for(uint32_t i = 0; i < 1600000; i++);
		GPIOA->ODR ^= GPIO_ODR_OD8;
	}
}
